services:
  gpt-load:
    image: ghcr.io/tbphp/gpt-load:1.3.0
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PANEL_APP_PORT_HTTP}:3001
    environment:
      - AUTH_KEY=${AUTH_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_DSN=${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@tcp(${PANEL_DB_HOST})/${PANEL_DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_DSN=redis://:${PANEL_REDIS_ROOT_PASSWORD}@${PANEL_REDIS_HOST}/0
    restart: always
    volumes:
      - ./data:/app/data
    stop_grace_period: ${SERVER_GRACEFUL_SHUTDOWN_TIMEOUT}s
    healthcheck:
      test: wget -q --spider -T 10 -O /dev/null http://localhost:3001/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
